//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking_Detail()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public decimal User_ID { get; set; }
        public decimal Seat_ID { get; set; }
        public decimal No_of_seats { get; set; }
        public decimal Route_ID { get; set; }
        public System.DateTime Booking_Date { get; set; }
        public System.DateTime Departure_Date { get; set; }
        public decimal Ticket_no { get; set; }
        public decimal Coach_ID { get; set; }
        public decimal Train_no { get; set; }
        public decimal Booking_ID { get; set; }
        public decimal Fare_ID { get; set; }
    
        public virtual Coach_Info Coach_Info { get; set; }
        public virtual Fare_Detail Fare_Detail { get; set; }
        public virtual Route_Detail Route_Detail { get; set; }
        public virtual Seat_Detail Seat_Detail { get; set; }
        public virtual Train_Info Train_Info { get; set; }
        public virtual User_Info User_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
