//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fare_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fare_Detail()
        {
            this.Booking_Detail = new HashSet<Booking_Detail>();
        }
    
        public decimal Route_ID { get; set; }
        public decimal Train_no { get; set; }
        public decimal Class_ID { get; set; }
        public decimal Fare { get; set; }
        public decimal Cancel_per { get; set; }
        public decimal Fare_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_Detail> Booking_Detail { get; set; }
        public virtual Class Class { get; set; }
        public virtual Route_Detail Route_Detail { get; set; }
        public virtual Train_Info Train_Info { get; set; }
    }
}
