//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public decimal Phone { get; set; }
        public string Password { get; set; }
        public decimal ID { get; set; }
    
        public virtual User_Info User_Info { get; set; }
    }
}
