//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public decimal Booking_ID { get; set; }
        public decimal Amount { get; set; }
        public decimal Atm_card_no { get; set; }
        public string PNR_no { get; set; }
        public decimal Payment_ID { get; set; }
    
        public virtual Booking_Detail Booking_Detail { get; set; }
    }
}
