//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_RRS_Context : DbContext
    {
        public DB_RRS_Context()
            : base("name=DB_RRS_Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking_Detail> Booking_Details { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Coach_Info> Coach_Infoes { get; set; }
        public virtual DbSet<Fare_Detail> Fare_Details { get; set; }
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Route_Detail> Route_Details { get; set; }
        public virtual DbSet<Schdule> Schdules { get; set; }
        public virtual DbSet<Seat_Detail> Seat_Details { get; set; }
        public virtual DbSet<Station_Detail> Station_Detail { get; set; }
        public virtual DbSet<Train_Info> Train_Infoes { get; set; }
        public virtual DbSet<Train_Route> Train_Routes { get; set; }
        public virtual DbSet<User_Info> User_Infoes { get; set; }
    }
}
