//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schdule
    {
        public decimal Train_no { get; set; }
        public Nullable<System.TimeSpan> Arrival_Time { get; set; }
        public Nullable<System.TimeSpan> Departure_Time { get; set; }
        public string Days { get; set; }
        public decimal Station_ID { get; set; }
        public decimal ID { get; set; }
    
        public virtual Station_Detail Station_Detail { get; set; }
        public virtual Train_Info Train_Info { get; set; }
    }
}
