//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Station_Detail()
        {
            this.Schdules = new HashSet<Schdule>();
        }
    
        public decimal Station_ID { get; set; }
        public string Station_Name { get; set; }
        public string Station_Code { get; set; }
        public string Railway_Division { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schdule> Schdules { get; set; }
    }
}
