//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train_Route
    {
        public decimal Train_no { get; set; }
        public decimal Route_ID { get; set; }
        public decimal ID { get; set; }
    
        public virtual Route_Detail Route_Detail { get; set; }
        public virtual Train_Info Train_Info { get; set; }
    }
}
