//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Info()
        {
            this.Booking_Detail = new HashSet<Booking_Detail>();
        }
    
        public string Name { get; set; }
        public decimal CNIC { get; set; }
        public decimal Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public decimal ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_Detail> Booking_Detail { get; set; }
        public virtual Login Login { get; set; }
    }
}
